version: '1.0'
services:
  postgres:
    #image: postgres:15.2-alpine
    image: 'postgres'
    ports:
      - '0.0.0.0:5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pa$$w0rd